### ISSUE TITLE
這個項目的問題

### ISSUE THREAD

**Issue by timmy61109** [ray1422/Fantastic-Filter-iOS#1]
你打算製作蘋果手機的應用嗎？

**Comment by ray1422** [comment]
是的，基本上就是這些了，但他載入模型的時候會報錯（實體機上）
不知道有沒有大神可以解決一下

**Comment by timmy61109** [comment]
希望我也可以試試，但我沒有蘋果手機，如果要裝在蘋果手機上面要怎麼用阿？

**Comment by ray1422** [comment]
您會需要一台蘋果電腦，在上面開xcode，連結手機後再點在手機上測試就行了。

**Comment by timmy61109** [comment]
好的，了解了，這樣什麼開發環境都沒有
